### ISSUE TITLE
error: cannot find symbol settings.setAppCachePath(...)

### ISSUE THREAD

**Issue by moein-keyvani-pur** [pichillilorenzo/flutter_inappwebview#1269]
when I add this package to my project it's ok but when I try to run the app I get the bottom error and use discover all packages I find this package has conflict with permission_handler: ^10.0.0 :
```C:\src\flutter_windows_2.10.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:280: error: cannot find symbol
      settings.setAppCachePath(options.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
C:\src\flutter_windows_2.10.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:494: error: cannot find symbol
      settings.setAppCacheEnabled(false);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
C:\src\flutter_windows_2.10.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:504: error: cannot find symbol
      settings.setAppCacheEnabled(true);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
C:\src\flutter_windows_2.10.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:515: error: cannot find symbol
        settings.setAppCachePath(ctx.getCacheDir().getAbsolutePath());
                ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
C:\src\flutter_windows_2.10.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:517: error: cannot find symbol
        settings.setAppCacheEnabled(true);

                ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
C:\src\flutter_windows_2.10.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:521: error: cannot find symbol
      settings.setAppCacheEnabled(false);

              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
```

```
 cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.2
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.3
  carousel_slider: ^4.1.1
  flutter_staggered_animations: ^1.0.0
  url_strategy: ^0.2.0
  # beamer: ^1.4.1+1
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  signalr_core: ^1.1.1
  lottie: ^1.3.0
  permission_handler: ^10.0.0
  connectivity_plus: ^2.3.5
  jalali_calendar:
    git: https://github.com/erfanegtfi/jalali_calendar
  file_picker: ^4.6.1
  # url_launcher: ^6.1.4
  # flutter_widget_from_html_core: ^0.8.5+3
  # webview_flutter: ^3.0.4
  # webview_flutter: ^3.0.4
  flutter_inappwebview:
  interactive_chart: ^0.3.4
  get_it: ^7.2.0
```
