### ISSUE TITLE
inappwebview shutdown trying to launch on Android API 33

### ISSUE THREAD

**Issue by chrisvidal** [pichillilorenzo/flutter_inappwebview#1436]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |        3.0.0       |
| Plugin version  |         5.7.1      |
| Android version |      API 33   emulator Galaxy A11      |
| macOS version   |    Monterey 12.6    on M1 chip       |

Device information: 

emulator Galaxy A11 API 33

## Description

**Expected behavior:** 
launch the app on the emulator

**Current behavior:** 

immediately crashes

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
Please, post more info about that, such as debug logs, code to replicate the issue, etc... Without any info, I can't do anything about it if there is an error.

**Comment by chrisvidal** [comment]
I have see no error, no log.

my `pubspec.yaml`

```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # nylo framework
  google_fonts: ^3.0.1
  analyzer: ^5.0.0
  intl: ^0.17.0
  nylo_framework: ^3.4.0
  pretty_dio_logger: ^1.2.0-beta-1

  flutter_localizations:
    sdk: flutter

  flutter_inappwebview: ^5.7.1

  url_launcher: ^6.1.6

  # push notifications
  onesignal_flutter: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4

  flutter_launcher_icons: ^0.10.0

# The following section is specific to flutter_launcher_icons.
flutter_icons:
  android: true
  # android: "launcher_icon"
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 19 # android min sdk min:16, default 21

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - lang/
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
```
