### ISSUE TITLE
Because every version of flutter_inappwebview from git depends on flutter_web_plugins from sdk which depends on js 0.6.3, every version of flutter_inappwebview from git requires js 0.6.3. So, because (App Name) depends on flutter_inappwebview from git which depends on js ^0.6.4, version solving failed.

### ISSUE THREAD

**Issue by BunnyBuddy** [pichillilorenzo/flutter_inappwebview#1545]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |2.10.4|
| Plugin version  |5.4.3+7|
| Android version |Android SDK version 33.0.0|
| iOS version     |16.2|
| macOS version   |12.6.3|
| Xcode version   |14.2|

## Description
We've been developing an Ecomerce seller app for the past few months (almost a year) and we were using **flutter_inappwebview** directly from git as a dependency and the repository we were using was,

`dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/CodeEagle/flutter_inappwebview`

We had to use this version (due to some issue) and everything was working fine, we don't know why but for some reason this git was deleted (a few days ago). So we decided to switch to the latest version or a more suitable version, but so far we've failed to resolve the following dependency error in our App.

**Expected behavior:** 
Should build the app

**Current behavior:** 
Now everytime we try to run **flutter pub get** it causes this issue,

`Because every version of flutter_inappwebview from git depends on flutter_web_plugins from sdk which depends on js 0.6.3, every version of flutter_inappwebview from git requires js 0.6.3.
So, because (our App) depends on flutter_inappwebview from git which depends on js ^0.6.4, version solving failed.
`

if we try to use an older version it throws conflicts with File Picker or some other plugins. We can't change the File Picker version as its the last version that supports our dart version and is being used vigorously throughout the App.

## Steps to reproduce
flutter clean
flutter pub cache clean
flutter pub get

I've attached the flutter doctor -v and pubspec.yaml

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.6.3 21G419 darwin-x64, locale en-PK)
    • Flutter version 2.10.4 at /Users/macbookpro/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • E1C2BAB4-E963-4C9E-BBC1-8220CB52EE2D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```
name: App
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/CodeEagle/flutter_inappwebview

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.0.0
  flutter_screenutil: ^5.0.1+2
  google_fonts: ^2.1.0
  connectivity_plus: ^2.1.0
  syncfusion_flutter_charts: ^19.4.50
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.5
  sqflite: ^2.0.0+3
  path_provider: ^2.0.11
  reorderable_grid_view: ^2.2.5
#  shimmer: ^2.0.0
  lottie: ^1.2.2
  syncfusion_flutter_datepicker: ^19.3.45
  flutter_typeahead: ^3.2.1
  google_place: ^0.4.0
  pull_to_refresh: ^2.0.0
  html_editor_enhanced: ^2.4.0+1
  multi_image_picker2: ^5.0.2
  dio: ^4.0.0
  flutter_chips_input: ^1.10.0
  keyboard_actions: ^3.4.7
  drop_cap_text: ^1.1.3
#  anim_search_bar: ^2.0.3
  searchbar_animation: ^0.0.4
  image_picker: ^0.8.5+3
  device_info_plus: ^4.0.0
  file_picker: ^4.6.1
  equatable: ^2.0.3
  badges: ^2.0.3
  pusher_channels_flutter: ^2.0.2
  share_plus: ^4.5.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
#  pusher_websocket_flutter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/JSON/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

Please guide us or explain us what can or can't we do in this scenario, we really appreciate your time and effort.
Thankyou

**Comment by harrowmykel** [comment]
Show your pubspec.yaml dependency list

**Comment by BunnyBuddy** [comment]
I've resolved this issue by,

Add this in your pubspec.yaml,

```
dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.2
```

And added this as a dependency,

`flutter_inappwebview: ^5.6.0+2`

Then restart your device, 

```
1. Flutter clean
2. Restart and invalidate cache in android studio
3. Flutter pub cache clean 
(this is the main step but this may cause issues in your App if there are too many dependencies and you've used some overridden dependencies too in that case try **Flutter pub cache repair**)
4. Flutter pub get
5. cd ios
6. pod update
```

My problem was that my pubspec.lock file was not updating for some reason even if I changed the version of this package in pubspec.yaml. 
And I needed the js library.
