### ISSUE TITLE
flutter_inappwebview iOS keep autoplay background video in full screen

### ISSUE THREAD

**Issue by Uhtredtb** [pichillilorenzo/flutter_inappwebview#1831]
Hi, I'm using this version in iOS keep autoplay background video in full screen, not happen on Android.

Please check this screen record:
https://monosnap.com/file/1BH4ee4p4Q23H9HrE2TtEatzvJihUq

```
flutter_inappwebview:
    git:
      url: https://github.com/vixez/flutter_inappwebview.git
      ref: fix-xcode-17

```

Please advice how to fix this bug?
Thank you
