### ISSUE TITLE
[Web] onLoadStart not invoked in Flutter 3.19.0 

### ISSUE THREAD

**Issue by elliotkhd** [pichillilorenzo/flutter_inappwebview#2026]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.19.0        |
| Plugin version        |      6.0.0         |
| Google Chrome version |        121.0.6167.160       |

I've tried to figure out what is going on and I found in web_support.js(line 22)
`var iframe = document.getElementById(iframeId);`
the iframe is null but the iframe element can be found in Chrome dev mode.

**Comment by MeenaFawzy** [comment]
I have the same exact issue and found out the same result which is the var iframe = document.getElementById(iframeId); is null in web_support.js (line 22)

**Comment by adsonpleal** [comment]
I have the same issue, flutter 3.19.0.

Is there any workaround for this issue?

**Comment by p-mazhnik** [comment]
Potentially related to https://github.com/flutter/flutter/issues/143922

**Comment by szotp-lc** [comment]
Until PR is merged you can use dependency override
```
dependency_overrides:
  flutter_inappwebview_web:
    git:
      url: https://github.com/p-mazhnik/flutter_inappwebview
      ref: web-fix
      path: flutter_inappwebview_web
```
