### ISSUE TITLE
[Xcode 16 Beta] Override evaluateJavaScript error when build 

### ISSUE THREAD

**Issue by GabriellArthur** [pichillilorenzo/flutter_inappwebview#2201]
Check the [Showcase](https://inappwebview.dev/showcase/) page to see an open list of Apps built with **Flutter** and **Flutter InAppWebView**.

If you are using the **Flutter InAppWebView** plugin and would like to add your App there,
follow the instruction on the [Submit App](https://inappwebview.dev/submit-app/) page!

<img width="471" alt="Captura de Tela 2024-06-27 às 15 50 47" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/71986202/6ebd2c2e-32f2-4ef5-9e72-2030da58e089">

ios WKWebView [Override evaluateJavaScript]

**Comment by suhailzoft** [comment]
Same issue here

**Comment by GabriellArthur** [comment]
I want to remove the `override` and remove some calls from it, so it may be breaking for you but for me it is working
https://github.com/GabriellArthur/flutter_inappwebview

**Comment by shubhamsinghmutualmobile** [comment]
> I want to remove the `override` and remove some calls from it, so it may be breaking for you but for me it is working https://github.com/GabriellArthur/flutter_inappwebview

This worked for me, thank you! 👏 Maybe you can raise a PR and see if it gets accepted?

**Comment by lucas-sesti** [comment]
Same issue here, hope they accept your PR.

**Comment by channoori** [comment]
In iOS 18.0 beta, the closure of the evaluateJavaScript method was changed in the iOS 18.0 beta, causing the error, so it seems that only the method needs to be changed in the override


Before
`public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil)`

After
`open override func evaluateJavaScript(_ javaScriptString: String, completionHandler: (@MainActor (Any?, (any Error)?) -> Void)? = nil)`

**Comment by hwr12** [comment]
@GabriellArthur 
Thanks for the [fork version](https://github.com/GabriellArthur/flutter_inappwebview) but I am getting this error also.
Any idea on how to fix this?

**Comment by hwr12** [comment]
> @GabriellArthur Thanks for the [fork version](https://github.com/GabriellArthur/flutter_inappwebview) but I am getting this error also. Any idea on how to fix this? ![IntelliJ IDEA-2024 07 16 14 33-003960](https://private-user-images.githubusercontent.com/54504396/348952962-e0a25c94-8439-434d-b2d2-ae38a932e946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDg0MDksIm5iZiI6MTcyMTEwODEwOSwicGF0aCI6Ii81NDUwNDM5Ni8zNDg5NTI5NjItZTBhMjVjOTQtODQzOS00MzRkLWIyZDItYWUzOGE5MzJlOTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1MzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYWMwNmMyMzhmMzdiMjgxZjMyMzFiNjcwOTJkMzA1ZDY3Njk5NDAxMDczNWQ5NWVjMTZhYTAxMTYxYTc3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KuVrnR-CfGISA4Osg2wplEXfwO4UnPpCh_bMaQNkWGM)

Fixed it. It was because I didn't update the xcodebuild cli version to the latest 16

**Comment by frapeti** [comment]
why is this closed

**Comment by maratbekovaidar** [comment]
> > @GabriellArthur Thanks for the [fork version](https://github.com/GabriellArthur/flutter_inappwebview) but I am getting this error also. Any idea on how to fix this? ![IntelliJ IDEA-2024 07 16 14 33-003960](https://private-user-images.githubusercontent.com/54504396/348952962-e0a25c94-8439-434d-b2d2-ae38a932e946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDg0MDksIm5iZiI6MTcyMTEwODEwOSwicGF0aCI6Ii81NDUwNDM5Ni8zNDg5NTI5NjItZTBhMjVjOTQtODQzOS00MzRkLWIyZDItYWUzOGE5MzJlOTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1MzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYWMwNmMyMzhmMzdiMjgxZjMyMzFiNjcwOTJkMzA1ZDY3Njk5NDAxMDczNWQ5NWVjMTZhYTAxMTYxYTc3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KuVrnR-CfGISA4Osg2wplEXfwO4UnPpCh_bMaQNkWGM)
> 
> Fixed it. It was because I didn't update the xcodebuild cli version to the latest 16

How you update xcodebuild cli version to 16?

**Comment by aokisinn** [comment]
Does anyone know why it's closed?

**Comment by ConnorDykes** [comment]
flutter_inappwebview:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
 
 this is giving my this error, any ideas?

 Could not find a file named "pubspec.yaml" in https://github.com/GabriellArthur/flutter_inappwebview.git caa355f66723630f9c9ce52ac8d592455dd37abb.

**Comment by shubhamsinghmutualmobile** [comment]
> flutter_inappwebview: git: url: https://github.com/GabriellArthur/flutter_inappwebview.git ref: master
> 
> this is giving my this error, any ideas?
> 
> Could not find a file named "pubspec.yaml" in https://github.com/GabriellArthur/flutter_inappwebview.git [caa355f](https://github.com/pichillilorenzo/flutter_inappwebview/commit/caa355f66723630f9c9ce52ac8d592455dd37abb).

Try adding `path` to your configuration like this:
```yaml
flutter_inappwebview:
  git:
  url: https://github.com/GabriellArthur/flutter_inappwebview.git
  # Add this
  path: flutter_inappwebview
  ref: master
```

**Comment by hansraj-flyzy** [comment]
> I want to remove the `override` and remove some calls from it, so it may be breaking for you but for me it is working https://github.com/GabriellArthur/flutter_inappwebview

Worked for me as well

**Comment by tnitsiri** [comment]
```
dependencies:
  flutter_inappwebview:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview
```

```
dependency_overrides:
  flutter_inappwebview_platform_interface:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_platform_interface
  flutter_inappwebview_android:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_android
  flutter_inappwebview_ios:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios
  flutter_inappwebview_macos:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos
  flutter_inappwebview_web:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_web

```
