### ISSUE TITLE
xcode 16 beta3 - ambiguous use of 'evaluateJavaScript(_:completionHandler:_)' build error

### ISSUE THREAD

**Issue by Hannah-mayhew1** [pichillilorenzo/flutter_inappwebview#2221]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |        3.22.2       |
| Plugin version        |        6.0.0       |
| Android version       |        x       |
| iOS version           |       18      |
| macOS version         |        x       |
| Xcode version         |        16 beta 3       |
| Google Chrome version |        x       |

Device information: 

## Description

**Expected behavior:** 
Build successful

**Current behavior:** 
![Screenshot 2024-07-12 at 16 43 55](https://github.com/user-attachments/assets/3f8ad010-809f-48f3-9b8b-f36eec9b4fb2)

**Notes** 
This is specifically an incompatibility with xcode16 and not iOS18. Xcode 16 is needed to install iOS18 simulators, however iOS18 simulators will run on xcode15. I was able to bypass the issue by rolling back xcode16 to 15.4 and running iOS18 there.

**Comment by Hannah-mayhew1** [comment]
[Linked issue](https://github.com/pichillilorenzo/flutter_inappwebview/issues/2201)

**Comment by allentown521** [comment]
same here

**Comment by dn1t** [comment]
Same error also occurs in flutter_inappwebview_macos (macOS 15)

**Comment by Mounix99** [comment]
+1

**Comment by frapeti** [comment]
+1

Broken build on iOS

**Comment by Hannah-mayhew1** [comment]
FYI, this is specifically an incompatibility with xcode16 and not iOS18. Xcode 16 is needed to install iOS18 simulators, however iOS18 simulators will run on xcode15. I was able to bypass the issue by rolling back xcode16 to 15.4 and running iOS18 there.

**Comment by allentown521** [comment]
> FYI, this is specifically an incompatibility with xcode16 and not iOS18. Xcode 16 is needed to install iOS18 simulators, however iOS18 simulators will run on xcode15. I was able to bypass the issue by rolling back xcode16 to 15.4 and running iOS18 there.

Yes, this is a temporary solution, next year the appstore will force the use of xcode16, will still face this problem, the library has been more than half a year without merging code!

**Comment by aokisinn** [comment]
Is this being fixed?

**Comment by ConnorDykes** [comment]
I updated Mac OS to beta versions and it won't let me downgrade to Xcode 15.4 now. I am stuck with Xcode 16, Any help would be appreciated.

**Comment by Mounix99** [comment]
@ConnorDykes  this should work
```dart
dependency_overrides:
  url_launcher_ios: 6.3.1
```

**Comment by landonmr** [comment]
same error, the dependency override didn't work for me, any update on this issue?

**Comment by mubahood** [comment]
I clicked on the error, and I deleted one like this, then it worked!

```
 public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
        if let applePayAPIEnabled = options?.applePayAPIEnabled, applePayAPIEnabled {
            if let completionHandler = completionHandler {
                completionHandler(nil, nil)
            }
            return
        }
        super.evaluateJavaScript(javaScriptString, completionHandler: completionHandler)
    } 
```

**Comment by ConnorDykes** [comment]
just updated to beta 6 and im getting this issue again

**Comment by ConnorDykes** [comment]
> I clicked on the error, and I deleted one like this, then it worked!
> 
> ```
>  public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
>         if let applePayAPIEnabled = options?.applePayAPIEnabled, applePayAPIEnabled {
>             if let completionHandler = completionHandler {
>                 completionHandler(nil, nil)
>             }
>             return
>         }
>         super.evaluateJavaScript(javaScriptString, completionHandler: completionHandler)
>     } 
> ```

what do you mean you deleted, when I delete it it give me errors

**Comment by tnitsiri** [comment]
```
dependencies:
  flutter_inappwebview:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview
```

```
dependency_overrides:
  flutter_inappwebview_platform_interface:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_platform_interface
  flutter_inappwebview_android:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_android
  flutter_inappwebview_ios:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios
  flutter_inappwebview_macos:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos
  flutter_inappwebview_web:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_web

```

**Comment by tnitsiri** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2201#issuecomment-2320102520

**Comment by tinaroh** [comment]
I noticed someone put out a fix for this, which is to update the signature of `evaluateJavaScript` https://github.com/pichillilorenzo/flutter_inappwebview/pull/2274

For now I'm overriding with it in `pubspec.yaml`:
```
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: 27fd339172572fe1b16cdcdae235b2a88f432e3c
      path: flutter_inappwebview_ios
```

**Comment by andychucs** [comment]
Just like what tinaroh commented. 

I make a little different changes based with other submit. I keep the override function `evaluateJavaScript` as public instead to delete or change as open. 

Also can use like following:
```
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios
```

**Comment by qwertylolman** [comment]
the xcode16 release is available, so this issue is a kind of critical. any updates?

**Comment by nabiarshad** [comment]
same issue after updating to Mac OS sequoia.
Xcode Version 16.0 (16A242d)

**Comment by Daniel-eXeX** [comment]
Seconding this. I'm now encountering this issue after XCode just auto-updated. Until a fix comes out, it appears that downgrading to XCode 15.4 will work around the issue.

For those mentioning the fork made by andychucs, it doesn't seem like it works (or I set it up wrong). I still got the exception even after adding the fork as a dependency override.

**Comment by qwertylolman** [comment]
> downgrading to XCode 15.4 will work around the issue.

are you able to downgrade the xcode? i cannot, as my macos also updated to sequoia. it just shows an error 'in order to use xcode you need to update to the latest version'

**Comment by Daniel-eXeX** [comment]
> are you able to downgrade the xcode? i cannot, as my macos also updated to sequoia. it just shows an error 'in order to use xcode you need to update to the latest version'

I was about to come back to comment on this. I was talking to a colleague who said that he could not downgrade because he'd updated his OS version. If you've already upgraded it, then you'll need another solution.

(As such, I'm now trying to get things working with XCode 16.0 again... 15.4 is a very temporary solution)

**Comment by rania-run** [comment]
I have the same issue, this temporary solution works for me.

> Just like what tinaroh commented.
> 
> I make a little different changes based on other pr. I keep the override function `evaluateJavaScript` as public instead of delete or change as open.
> 
> Also can use like following:
> 
> ```
>   flutter_inappwebview_ios:
>     git:
>       url: https://github.com/andychucs/flutter_inappwebview.git
>       ref: master
>       path: flutter_inappwebview_ios
> ```

**Comment by scriptam** [comment]
For those looking for a fast workaround for `Xcode 16.0 (16A242d)`, the following is worth a consideration: <https://github.com/pichillilorenzo/flutter_inappwebview/pull/2274#issue-2523140652>

Credit and thanks go to @andychucs

Add the following to your `pubspec.yaml`

```yaml
dependencies:
  # rest of your dependencies ...
  flutter_inappwebview: ^6.0.0 

# Add the following dependency overrides for iOS & macOS, as needed -->
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

  flutter_inappwebview_macos:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos
# <--
```
