### ISSUE TITLE
flutter App crashes on android 7 Phone 

### ISSUE THREAD

**Issue by server2245** [pichillilorenzo/flutter_inappwebview#289]
## Environment

**Flutter version:** 1.12.13+hotfix.5
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    
Sony Android 7 phone
## Description

**Expected behavior:** 
App Open fine
**Current behavior:** 
App never stops always crashes
## Steps to reproduce
Include flutter_inappwebview: plugin in YAML file
flutter run
App. always crashes and never opens, No logs in debug mode.
I already made MinSDKversion 17 and 
<uses-permission android:name="android.permission.INTERNET" />

**Comment by server2245** [comment]
I was able to fix this issue with below YAML change

```
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
```
