### ISSUE TITLE
Loading local reesources

### ISSUE THREAD

**Issue by juanestebanchaparromachete** [pichillilorenzo/flutter_inappwebview#425]
when i load the  index.html file and main.js file works perfect but  I need to load 3 .png file that are in the same path in the flutter assets that  are use in the main.js these files never load. this is the code 

class MapsPage extends StatefulWidget {
  @override
  _MapsPageState createState() => _MapsPageState();
}

class _MapsPageState extends StateMVC {
  _MapsPageState() : super(MapsController()) {
    controller = MapsController.con;
  }

  MapsController controller;
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  InAppWebViewController webView;
  String url = "";
  double progress = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: InAppWebView(
      initialHeaders: {},
      initialOptions: InAppWebViewGroupOptions(
          crossPlatform: InAppWebViewOptions(
        debuggingEnabled: true,
      )),
      onWebViewCreated: (InAppWebViewController controller) {
        webView = controller;
        loadAsset();
      },
      onProgressChanged: (InAppWebViewController controller, int progress) {
        setState(() {
          this.progress = progress / 100;
        });
      },
    ));
  }

  loadAsset() async {
    await webView.loadFile(assetFilePath: 'assets/www/test.jpeg');
    await webView.loadFile(assetFilePath: 'assets/www/P1.png');
    await webView.loadFile(assetFilePath: 'assets/www/P2.png');
    await webView.loadFile(assetFilePath: 'assets/www/P3.png');
    await webView.loadFile(assetFilePath: 'assets/www/P4.png');

    var fivenFile = rootBundle.loadString('assets/www/index.html');
    fivenFile.then((String html) {
      webView.loadData(data: html);
    });
    await webView.injectJavascriptFileFromAsset(
        assetFilePath: 'assets/www/main.js');

  }
}

I need to know the path where the file were loaded. thanks

**Comment by pichillilorenzo** [comment]
What you are doing is not correct.
The `loadFile` method should be used to load the main resource, for example, your `index.html` and not every single asset file.

`loadFile` is similar to `loadUrl`, the difference is that on `loadUrl` you are using an URL to load the website, instead, on `loadFile` you are using the file path to load the local website.

Here is an example:
```dart
InAppWebView(
  initialFile: "assests/www/index.html",
  initialOptions: InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
          debuggingEnabled: true
      )
  ),
  onWebViewCreated: (InAppWebViewController controller) {
    webView = controller;
  },

...
```

Inside `assests/www/index.html`, you will have something like this:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <title>InAppWebViewInitialFileTest</title>
    </head>
    <body>
        <img src="www/test.jpeg" alt="">
        <img src="www/P1.png" alt="">
        <img src="www/P2.png" alt="">
        <img src="www/P3.png" alt="">
        <img src="www/P4.png" alt="">

        <script src="www/main.js"></script>
    </body>
</html>
```

Also, you need to declare your asset files inside `pubspec.yaml`, otherwise, Flutter won't recognize them. So, your `pubspec.yaml` file would have:
```yaml

...

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  
  assets:
    - assets/www/index.html
    - assets/www/main.js
    - assets/www/test.jpeg
    - assets/www/P1.png
    - assets/www/P2.png
    - assets/www/P3.png
    - assets/www/P4.png
...
```
