### ISSUE TITLE
ShouldInterceptAjaxRequest method is never triggered

### ISSUE THREAD

**Issue by xingfudeshi** [pichillilorenzo/flutter_inappwebview#502]
I am a fresher with Flutter, this plugin is great, but I am having some problems that have been bothering me for many days, I don't know what went wrong. ShouldInterceptAjaxRequest method is never triggered.please check out my code.please help me.

https://gitee.com/xingfudeshi/my_test

**Comment by xingfudeshi** [comment]
I just tested it and this example works(https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/example/test_driver/in_app_webview_ajax_test.dart), but when I change the version to 4.0.0+4, I can't trigger ajax-related methods.
```
dependencies:
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_downloader: ^1.4.4
  path_provider: ^1.6.9
  permission_handler: ^5.0.0+hotfix.6
  url_launcher: ^5.4.11
  # connectivity: ^0.4.5+6
  flutter_inappwebview: 4.0.0+4
    #path: ../
```
