### ISSUE TITLE
My router doesn't interact with JS properly

### ISSUE THREAD

**Issue by JingGaoXu** [pichillilorenzo/flutter_inappwebview#513]
Flutter:
```dart
onWebViewCreated: (InAppWebViewController controller) {
             controller.addJavaScriptHandler(handlerName: JSFunctionName.jsCallFlutter, callback: (arguments) {
             print(arguments.toString());
            });

          }
```
JS:
```javascript
 window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
            console.log(event);
            window.flutter_inappwebview.callHandler('jsCallFlutter', res).then(function(result) {
              console.log( result);
            });
          });
```

**Comment by JingGaoXu** [comment]
window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {}
It doesn't work here

**Comment by pichillilorenzo** [comment]
Could you try the Master version of this repository? It should be fixed with the next version 5.0.0

```yaml
flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
```
