### ISSUE TITLE
how to add WebView.platform = SurfaceAndroidWebView() in flutter_inappwebview

### ISSUE THREAD

**Issue by wangxingxing123654** [pichillilorenzo/flutter_inappwebview#563]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by ycv005** [comment]
Download the plugin via the github like this

```
  flutter_inappwebview:
      git:
        url: https://github.com/pichillilorenzo/flutter_inappwebview.git
        ref: master
```

```
initialOptions: InAppWebViewGroupOptions(
                  android: AndroidInAppWebViewOptions(
                    disableDefaultErrorPage: true,
                    useHybridComposition: true, // here is what you need
                  ),
                  crossPlatform: InAppWebViewOptions(
                    useShouldOverrideUrlLoading: true,
                  ),
                ),
```
