### ISSUE TITLE
"useHybridComposition" isn't defined

### ISSUE THREAD

**Issue by ReaganRealones** [pichillilorenzo/flutter_inappwebview#608]
Very simple here, the current package version does not seem to be published on pub.dev. The [link to it is here](https://pub.dev/packages/flutter_inappwebview). So the property isnt defined yet.Checking on the repo here, version is 5, while [here](https://pub.dev/packages/flutter_inappwebview) it's 4.0.0+4

**Comment by ycv005** [comment]
You are not using latest version. It is only available on the github for now. Put following in your pubspec.yaml file
```
  flutter_inappwebview:
      git:
        url: https://github.com/pichillilorenzo/flutter_inappwebview.git
        ref: master
```
