### ISSUE TITLE
The ability to update the application, print and download files

### ISSUE THREAD

**Issue by omerosmanoglu** [pichillilorenzo/flutter_inappwebview#775]
- [ok] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [ok] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [ok] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [ok] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        >=2.1.0 <3.0.0       |
| Plugin version       |      ^4.0.0+4         |
| Android version      |    10          |
| iOS version          |       x        |
| Xcode version        |        x       |

Device information: Xiomi Mi A2 Lite

I purchased an application from codecanyon that uses your library. But I can't download files (a href=x.pdf,y.xls,z.doc etc.) and window.print () doesn't work. The app I purchased is using the ^ 4.0.0 + 4 version. How can I update this?

In my research I was told that I can do this with pubspec.yaml, but I have no information on how to do it.

pubspec.yaml
```
name: flyweb
description: FlyWeb application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^0.5.7
  onesignal_flutter: ^2.4.0
  flutter_spinkit: ^4.1.2+1
  http: ^0.12.1
  page_transition: ^1.1.5
  share: ^0.6.4
  modal_progress_hud: ^0.1.3
  launch_review: ^2.0.0
  firebase_admob: ^0.9.3
  url_launcher: ^5.4.5
  geolocator: ^5.3.2+2
  store_redirect: ^1.0.2
  webview_flutter: ^0.3.22+1
  connectivity: ^0.4.8+6
  provider: ^4.3.2+2
  global_configuration: ^1.5.0
  location: ^3.0.2
  flutter_inappwebview: ^4.0.0+4
  permission_handler: ^5.0.1+1
  package_info: ^0.4.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/flag/
    - assets/cfg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
